# Modules

In [1]:
#Importación de biblioteca numpy y renombrarla como np. Esta biblioteca 
# nos permitira trabajar con arreglos multidimensionales.
import numpy as np 
#Importación de biblioteca pandas y renombrarla como pd. Esta biblioteca 
# nos ayuda a manipular a analizar datos estructurados como DataFrames. 
# Un DF es como una tabla de excel.
import pandas as pd
#Importación de biblioteca math. Esta nos ayuda a utilizar funciones 
# matemáticas básicas.
import math
#La importación de plotly nos ayudará a poder utilizar objetos gráficos 
# como líneas, puntos y superficies.
import plotly.graph_objects as go
#Importar el módulo de distancia nos proporcionará funciones para poder 
# medir distancias en el espacio.
from scipy.spatial import distance
#Esta distribución (wrapcauchy) se utiliza para modelar ángulos o 
# direcciones en trayectorias, como en procesos estocásticos con giros.
from scipy.stats import wrapcauchy
#Al importar cauchy, podremos modelar datos que trabajan con colas pesadas, 
# específicamente nos va a servir para modelar CRW.
from scipy.stats import cauchy
#Con esta siguiente distribución podremos modelar datos con saltos grandes 
# e inesperados como el movimiento Browniano de Lévy.
from scipy.stats import levy_stable

## Vec2dClass

In [2]:
################# http://www.pygame.org/wiki/2DVectorClass ##################

#Qué hace esta parte?
#Estamos definiendo una clase llamada Vec2d, que hereda de 
# object, lo que es estándar en Python 2 y también compatible 
# con Python 3.

#Función: Esta clase es un modelo de un vector en 2D y proporciona 
# soporte para operadores matemáticos como suma y resta y funciones 
# útiles para manipulaciones vectoriales.
class Vec2d(object):
    """2d vector class, supports vector and scalar operators,
       and also provides a bunch of high level functions
       """
    #Esta siguiente línea __slots__ optimiza la memoria al defiir los 
    # atributos de la clase "x" y "y", restringiendo la creación de otros 
    # atributos. Esto es útil en aplicaciones de alta eficiencia, ya 
    # que evita el uso de un diccionario interno para almacenar atributos.
    __slots__ = ['x', 'y']

#Aquí vamos a inicializar un objeto de la clase Vec2d. __init__ es el 
# constructor que define cómo se crea un vector.
#Los parámetros que vamos a usar son:
#x_or_pair: Puede ser un par de valores, una lista, una tupla con dos 
# elementos o solo valor "x".
#y: Es opcional. Si no se proporciona, x_or_pair debe ser un par; si 
# se proporcina, x_or_pair es tratado como el valor de "x" y "y", es el valor de "y".
    def __init__(self, x_or_pair, y = None):
        if y == None:            
            self.x = x_or_pair[0]
            self.y = x_or_pair[1]
        else:
            self.x = x_or_pair
            self.y = y
            
    # Addition
    #Si "other" es otro Vec2d, suma componente a componente, si "other" tiene un método __getitem__
    # (es una lista o una tupla), suma los elementos correspondientes. Si "other" es un 
    # escalar, suma ese valor a ambos componentes "x" y "y".
    def __add__(self, other):
        if isinstance(other, Vec2d):
            return Vec2d(self.x + other.x, self.y + other.y)
        elif hasattr(other, "__getitem__"):
            return Vec2d(self.x + other[0], self.y + other[1])
        else:
            return Vec2d(self.x + other, self.y + other)

    # Subtraction
    #Lo mismo que el anterior, pero resta en vez de sumar.
    def __sub__(self, other):
        if isinstance(other, Vec2d):
            return Vec2d(self.x - other.x, self.y - other.y)
        elif (hasattr(other, "__getitem__")):
            return Vec2d(self.x - other[0], self.y - other[1])
        else:
            return Vec2d(self.x - other, self.y - other)
    
    # Vector length
    #Esta parte servirá para calcular la longitud o magnitud del vector utilizando el teorema de pitágoras.
    def get_length(self):
        return math.sqrt(self.x**2 + self.y**2)
    
    # rotate vector
    #Esta parte rota el vector por un ángulo dado en radianes.
    def rotated(self, angle):        
        cos = math.cos(angle)
        sin = math.sin(angle)
        x = self.x*cos - self.y*sin
        y = self.x*sin + self.y*cos
        return Vec2d(x, y)

## Brownian Motion

In [3]:
#Selecciona aleatoriamente un ángulo entre cuatro posibles valores: 
# 0, pi medios (90 grados), pi (180 grados) y 3 pi medios (270 grados). 
# Esta selección aleatoria se utiliza para determinar la dirección de 
# giro o rotación de un vector o movimieto en un plano bidimensional.
turn_angle=np.random.choice([0,np.pi/2,np.pi,3*np.pi/2])

In [7]:
#La función pd.read_csv() es una función de la librería de Pandas 
# que se utiliza para leer archivos CSV y convertirlos en un DataFrame de 
# Pandas. Se espera que el archivo esté en el mismo directorio desde 
# donde se está ejecutanto el script de Python. El resultado se guarda 
# en la variable: "BM_2d_df_3".
BM_2d_df_3=pd.read_csv('brownian_3.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'brownian_3.csv'

In [ ]:
met_tad = pd.read_csv('met_df_3.csv')
met_tad

     TA_CRW_6  TA_CRW_9
0    1.526081  0.131243
1   -1.995115 -0.116685
2    1.248337  0.310765
3    0.478471 -0.086050
4   -0.547363  1.131171
..        ...       ...
993 -0.615127 -0.199832
994 -0.762372 -0.877469
995  0.024496  0.140115
996 -0.637645  0.044725
997 -0.157005  0.619102

[998 rows x 2 columns]

In [ ]:
met_tad = pd.read_csv('met_df_3.csv')
met_tad

     TA_CRW_6  TA_CRW_9
0    1.526081  0.131243
1   -1.995115 -0.116685
2    1.248337  0.310765
3    0.478471 -0.086050
4   -0.547363  1.131171
..        ...       ...
993 -0.615127 -0.199832
994 -0.762372 -0.877469
995  0.024496  0.140115
996 -0.637645  0.044725
997 -0.157005  0.619102

[998 rows x 2 columns]